project:
  type: website
  output-dir: docs

website:
  title: "pg-lab"
  favicon: favicon.png
  repo-url: https://github.com/luisdva/pg-lab
  site-url: https://luisdva.github.io/pg-lab
format:
  html:
    theme:
      light:
        - cosmo
        - brand
      dark:
        - darkly
        - brand
    css: styles.css
    toc: true




babelquarto:
  icon: "bi bi-flag"
  languagelinks: navbar
  languagecodes:
  - name: en
    text: "English"
  - name: es
    text: "Español"
  mainlanguage: 'es'
  languages: ['en']
title-en: "pg-lab"
description-en: description in en
author-en: author in en
lang: es
