project:
  type: website
  output-dir: docs

website:
  title: "maevolab"
  favicon: favicon.png
  repo-url: https://github.com/maevolabMX/pg-lab
  site-url: https://maevolab.mx
format:
  html:
    theme:
      light:
        - cosmo
        - brand
      dark:
        - darkly
        - brand
    css: styles.css
    toc: true




babelquarto:
  icon: "bi bi-flag"
  languagelinks: navbar
  languagecodes:
  - name: en
    text: "English"
  - name: es
    text: "Español"
  mainlanguage: 'es'
  languages: ['en']
title-en: "maevolab"
description-en: description in en
author-en: author in en
lang: es
