---
title: "Investigación"
toc: false
format: html
---

Nuestros intereses de investigación abarcan una amplia gama de temas relacionados con los campos de la macroecología, macroevolución, biogeografía, ecología de comunidades y teórica, eco-filogenética, métodos comparativos filogenéticos y biología de la conservación. Estamos particularmente interesados en estudiar patrones geográficos de biodiversidad y la estructura de comunidades ecológicas, así como en comprender las causas que originan, mantienen y alteran dichos patrones.  

Nos enfocamos principalmente en vertebrados, pero también trabajamos con otros taxones, incluyendo insectos y plantas. Actualmente, integramos enfoques ecológicos y evolutivos para estudiar patrones biogeográficos y filogenéticos, su relación con el entorno y la aplicación de dichos estudios a evaluaciones y acciones de conservación informadas.

## Intereses

- Macroecología
- Biogeografía
- Macroevolución
- Biogeografía de la Conservación
- Estadísticas Espaciales
- Métodos Comparativos Filogenéticos
